name: Release
on:
  push:
    branches:
    - main

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
    - name: Install Goreleaser
      run: go install github.com/goreleaser/goreleaser@latest
    - name: Run Goreleaser
      run: |
        goreleaser release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
